[source.crates-io]
replace-with = "Tools_PublicPackages"

[alias]
xtask = "run -p xtask --"

[registries]
Tools_PublicPackages = { index = "sparse+https://pkgs.dev.azure.com/sysinternals/_packaging/Tools_PublicPackages/Cargo/index/" }