[package]
name = "procdump"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "ProcDump process dump generation and monitoring API"
repository = "https://github.com/microsoft/ProcDump-for-Linux"
readme = "README.md"
publish = ["Tools_PublicPackages"]

[lib]
path = "src/lib.rs"

[features]
default = []
monitor = []
dotnet-triggers = ["monitor"]
restrack = ["monitor", "dep:blazesym", "dep:libbpf-cargo", "dep:libbpf-rs"]
full = ["dotnet-triggers", "restrack"]

[dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
blazesym = { version = "=0.2.3", optional = true }
libbpf-rs = { version = "0.27.0", optional = true }

[target.'cfg(target_os = "linux")'.build-dependencies]
libbpf-cargo = { version = "0.27.0", optional = true }

[lints]
workspace = true